export const coreVersion = '0.1.0';
export { scanZstdFrames, ZSTD_MAGIC } from './zstd-frames.js';
export type { ZstdFrame, ZstdScanResult } from './zstd-frames.js';
export { decodeZstdLog } from './decompress.js';
export type { DecodedZstdLog } from './decompress.js';
export { traceEventSchema, traceTurnSchema, traceSessionSchema, statReportSchema, traceJsonSchema } from './trace-schema.js';
export type { TraceEvent, TraceTurn, TraceSession, StatReport } from './trace-schema.js';
export { buildTraceTree } from './tree.js';
export type { TreeNode, TreeNodeKind, TraceTree } from './tree.js';
export { aggregateStats } from './stat.js';
